/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prototipobisca;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author alexandre-kde
 */
public class JanelaInicial extends javax.swing.JFrame {

    /**
     * @return the txtNomeJogador
     */
    public javax.swing.JTextField getTxtNomeJogador() {
        return txtNomeJogador;
    }

    /**
     * @param txtNomeJogador the txtNomeJogador to set
     */
    public void setTxtNomeJogador(javax.swing.JTextField txtNomeJogador) {
        this.txtNomeJogador = txtNomeJogador;
    }
        
    public JanelaInicial() {
        initComponents();
        //solicitarNomeJogador();
        //setVisible(true);
    }
    
    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible) {
            solicitarNomeJogador();
        }
    }
    
    public void solicitarNomeJogador() {
        nome = JOptionPane.showInputDialog(null,
                "Informe seu nome", "Bisca",JOptionPane.QUESTION_MESSAGE);
        getTxtNomeJogador().setText(nome);
    }
    
    /*public void alterarNomeJogador() {
        String nome = JOptionPane.showInputDialog(null,
                "Informe um novo nome", "Alterar nome",
                JOptionPane.QUESTION_MESSAGE);
        txtNomeJogador.setText(nome);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNomeJogador = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ConectarJogo = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(220, 210, 179));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome Do Jogador"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNomeJogador.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        txtNomeJogador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeJogadorMouseClicked(evt);
            }
        });
        jPanel1.add(txtNomeJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 330, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton1.setText("Hospedar Jogo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hospedar(evt);
            }
        });

        ConectarJogo.setBackground(new java.awt.Color(204, 204, 204));
        ConectarJogo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        ConectarJogo.setText("Conectar a Jogo");
        ConectarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarJogo(evt);
            }
        });

        Alterar.setBackground(new java.awt.Color(204, 204, 204));
        Alterar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAlterar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alterar, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConectarJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConectarJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Hospedar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hospedar
        JanelaHospedagem hospedagem = new JanelaHospedagem();
        hospedagem.setVisible(true);
        (hospedagem.getTxtJogadoresConectados()).setText(nome);
        hospedagem.setVisible(true);
        
    }//GEN-LAST:event_Hospedar

    private void ButtonAlterar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAlterar
       solicitarNomeJogador();
    }//GEN-LAST:event_ButtonAlterar

    private void ConectarJogo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarJogo
        JanelaEntrarJogo entrarNoJogo = new JanelaEntrarJogo();
        entrarNoJogo.setVisible(true);
    }//GEN-LAST:event_ConectarJogo

    private void txtNomeJogadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeJogadorMouseClicked
        getTxtNomeJogador().setEnabled(false);
    }//GEN-LAST:event_txtNomeJogadorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaInicial().setVisible(true);
            }
        });
    }
    
    
   public String nome = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton ConectarJogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNomeJogador;
    // End of variables declaration//GEN-END:variables


 
}
